# Generated by Django 5.2.11 on 2026-03-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
