# Generated by Django 5.2.11 on 2026-03-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="enrollment_date",
        ),
    ]
