# Generated by Django 5.2.11 on 2026-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_student_enrollment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(default="Unknown", max_length=100),
        ),
    ]
